# ██████╗  ██████╗ █████╗
# ██╔══██╗██╔════╝██╔══██╗
# ██║  ██║██║     ███████║
# ██║  ██║██║     ██╔══██║
# ██████╔╝╚██████╗██║  ██║
# ╚═════╝  ╚═════╝╚═╝  ╚═╝
# DEPARTAMENTO DE ENGENHARIA DE COMPUTACAO E AUTOMACAO
# UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE, NATAL/RN
#
# (C) 2023 CARLOS M D VIEGAS
#
# This is a docker-compose file that creates a stack of 
# Apache Hadoop 3.3.5 containers with Spark 3.3.2
#

version: '3.9'

services:
  node-master:
    container_name: node-master
    hostname: node-master
    image: hadoopcluster/hadoop-spark:v4
    build:
      context: .
      args:
        USER: spark
        PASS: spark
    tty: true
    restart: unless-stopped
    networks:
      hadoop_network:
        ipv4_address: 172.18.0.2
    ports:
      - 9870:9870
      - 8088:8088
      - 18080:18080
      - "2222:22"
    volumes: 
      - ./apps:/home/spark/apps
      - spark-data-master:/home/spark/

  slave1:
    container_name: slave1
    hostname: slave1
    image: hadoopcluster/hadoop-spark:v4
    tty: true
    restart: unless-stopped
    networks:
      hadoop_network:
        ipv4_address: 172.18.0.3
    depends_on:
      - node-master
    volumes: 
      - ./apps:/home/spark/apps
      - spark-data-slave1:/home/spark/

  slave2:
    container_name: slave2
    hostname: slave2
    image: hadoopcluster/hadoop-spark:v4
    tty: true
    restart: unless-stopped
    networks:
      hadoop_network:
        ipv4_address: 172.18.0.4
    depends_on:
      - node-master
    volumes: 
      - ./apps:/home/spark/apps
      - spark-data-slave2:/home/spark/

networks:
  hadoop_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24

volumes:
  spark-data-master:
  spark-data-slave1:
  spark-data-slave2:
